import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { useDispatch } from 'react-redux'
import { addProduct } from '../redux/productSlice'


const products =[
  {
    name: "Mango",
    price : 20
  },
  {
    name: "Apple",
    price : 24
  },
  {
    name: "Banana",
    price : 20
  },
  {
    name: "Orange",
    price : 20
  },
  {
    name: "Alu",
    price : 20
  }
]
export default function Home() {
  const dispatch = useDispatch()
  return (
    <div className={styles.container}>
      
      <Head>
        <title>Redux</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <div className='mt-16'>
        <Link href='/cart'>
          <button className='bg-orange-500  p-3 text-white font-bold rounded-xl '>Cart</button>
        </Link>
        {
          products.map((product,i) => <div key={i} className='flex flex-row justify-between text-white bg-slate-900 rounded-xl p-10 text-lg font-bold mt-6'>
          <div>
          <h1>Product Name: {product.name}</h1>
           <h1>Product price: ${product.price}</h1>
          </div>
            <button onClick={()=>dispatch(addProduct(product))} className='bg-white text-black p-4 rounded-lg'>Add To Cart</button>
      </div>)
        }
            
            

       </div>
    
    </div>
  )
}
